@startuml table_households
class households {
    + id : INTEGER [PK]
    --
    * household_code : VARCHAR(255) [UNIQUE]
    owner_id : INTEGER [FK]
    member_count : INTEGER
    address_street : VARCHAR(255)
    address_ward : VARCHAR(255)
    address_district : VARCHAR(255)
    address : VARCHAR(255)
    area : NUMERIC(10,2)
    status : VARCHAR(50)
    created_date : DATE
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
}
@enduml
